apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 40  # This value will be replaced dynamically
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 8Gi
